"""
Pydantic Document Models
=========================
Each class represents the schema of a Supabase Postgres row.
Used to **validate** data before writing and **parse** data after reading.
These are plain Pydantic BaseModel classes (NOT SQLAlchemy ORM).
"""

import datetime
from typing import Optional
from pydantic import BaseModel, Field


def _utc_now() -> datetime.datetime:
    return datetime.datetime.now(datetime.timezone.utc)


# ── Users ────────────────────────────────────────────────────────────────────

class User(BaseModel):
    id: Optional[str] = None  # Supabase UUID (cast to str)
    name: str
    email: str
    password_hash: Optional[str] = None  # Nullable for pure Google OAuth users
    auth_provider: str = "local"          # 'local' | 'google'
    google_id: Optional[str] = None
    role: str = "viewer"                  # 'admin' | 'analyst' | 'viewer'
    is_active: bool = True
    created_at: datetime.datetime = Field(default_factory=_utc_now)

    def to_supabase_dict(self) -> dict:
        """Serialize for Supabase write, omitting the `id` (auto-generated by DB)."""
        return self.model_dump(mode='json', exclude={"id"}, exclude_none=True)

    @classmethod
    def from_supabase_row(cls, row: dict) -> "User":
        """Parse a Supabase row dict into a User model."""
        return cls(**row)


# ── Password Resets ──────────────────────────────────────────────────────────

class PasswordReset(BaseModel):
    id: Optional[str] = None
    user_id: str  # references users.id
    token_hash: str
    expires_at: datetime.datetime
    used: bool = False
    created_at: datetime.datetime = Field(default_factory=_utc_now)

    def to_supabase_dict(self) -> dict:
        return self.model_dump(mode='json', exclude={"id"}, exclude_none=True)

    @classmethod
    def from_supabase_row(cls, row: dict) -> "PasswordReset":
        return cls(**row)


# ── Scans ────────────────────────────────────────────────────────────────────

class Scan(BaseModel):
    id: Optional[str] = None
    started_at: datetime.datetime = Field(default_factory=_utc_now)
    finished_at: Optional[datetime.datetime] = None
    source_type: str            # 'network_dns_log' | 'extensions_export' | 'combined'
    status: str = "running"     # 'running' | 'completed' | 'failed'
    triggered_by: Optional[str] = None  # references users.id

    def to_supabase_dict(self) -> dict:
        return self.model_dump(mode='json', exclude={"id"}, exclude_none=True)

    @classmethod
    def from_supabase_row(cls, row: dict) -> "Scan":
        return cls(**row)


# ── Findings ─────────────────────────────────────────────────────────────────

class Finding(BaseModel):
    id: Optional[str] = None
    scan_id: str                # references scans.id
    entity_type: str            # 'domain' | 'extension'
    entity_value: str
    category: str
    vendor: str
    sanction_status: str = "unknown"  # 'sanctioned' | 'unsanctioned' | 'unknown'
    data_exposure_bytes: int = 0
    users_affected: int = 1
    event_count: int = 1
    risk_score: float = 0.0
    risk_tier: str = "low"      # 'low' | 'medium' | 'high' | 'critical'
    created_at: datetime.datetime = Field(default_factory=_utc_now)

    def to_supabase_dict(self) -> dict:
        return self.model_dump(mode='json', exclude={"id"}, exclude_none=True)

    @classmethod
    def from_supabase_row(cls, row: dict) -> "Finding":
        return cls(**row)


# ── Fingerprint Domains ──────────────────────────────────────────────────────

class FingerprintDomain(BaseModel):
    id: Optional[str] = None
    domain: str
    category: str
    vendor: str
    sanctioned: bool = False

    def to_supabase_dict(self) -> dict:
        return self.model_dump(mode='json', exclude={"id"}, exclude_none=True)

    @classmethod
    def from_supabase_row(cls, row: dict) -> "FingerprintDomain":
        return cls(**row)


# ── Fingerprint Extensions ───────────────────────────────────────────────────

class FingerprintExtension(BaseModel):
    id: Optional[str] = None
    name: str
    category: str
    vendor: str
    sanctioned: bool = False

    def to_supabase_dict(self) -> dict:
        return self.model_dump(mode='json', exclude={"id"}, exclude_none=True)

    @classmethod
    def from_supabase_row(cls, row: dict) -> "FingerprintExtension":
        return cls(**row)


# ── Agent Investigations ─────────────────────────────────────────────────────

class AgentInvestigation(BaseModel):
    id: Optional[str] = None
    finding_id: str             # references findings.id
    summary: str
    recommendation: str         # 'block' | 'monitor' | 'escalate'
    rationale: str
    confidence: float = 0.9
    created_at: datetime.datetime = Field(default_factory=_utc_now)

    def to_supabase_dict(self) -> dict:
        return self.model_dump(mode='json', exclude={"id"}, exclude_none=True)

    @classmethod
    def from_supabase_row(cls, row: dict) -> "AgentInvestigation":
        return cls(**row)


# ── Alert Log ────────────────────────────────────────────────────────────────

class AlertLog(BaseModel):
    id: Optional[str] = None
    finding_id: str             # references findings.id
    channel: str                # 'slack' | 'email'
    sent_at: datetime.datetime = Field(default_factory=_utc_now)
    status: str = "sent"        # 'sent' | 'failed' | 'disabled'

    def to_supabase_dict(self) -> dict:
        return self.model_dump(mode='json', exclude={"id"}, exclude_none=True)

    @classmethod
    def from_supabase_row(cls, row: dict) -> "AlertLog":
        return cls(**row)
